# Generated by Django 4.1.1 on 2022-10-06 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='llanta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('descripccion', models.TextField(null=True, verbose_name='Descripcion')),
            ],
        ),
    ]
