# Generated by Django 4.1.1 on 2022-10-06 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_llantas', '0002_rename_descripccion_llanta_descripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='llanta',
            old_name='titulo',
            new_name='fabricante',
        ),
    ]
