# Generated by Django 4.1.1 on 2022-10-06 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_llantas', '0003_rename_titulo_llanta_fabricante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='llanta',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='llanta',
            name='ancho',
            field=models.CharField(max_length=100, null=True, verbose_name='Ancho'),
        ),
        migrations.AddField(
            model_name='llanta',
            name='indiceCarga',
            field=models.CharField(max_length=100, null=True, verbose_name='Indice de Carga'),
        ),
        migrations.AddField(
            model_name='llanta',
            name='indiceVelocidad',
            field=models.CharField(max_length=100, null=True, verbose_name='Indice de Velocidad'),
        ),
        migrations.AddField(
            model_name='llanta',
            name='lonas',
            field=models.CharField(max_length=100, null=True, verbose_name='Lonas'),
        ),
        migrations.AddField(
            model_name='llanta',
            name='perfil',
            field=models.CharField(max_length=100, null=True, verbose_name='Perfil'),
        ),
        migrations.AddField(
            model_name='llanta',
            name='rin',
            field=models.CharField(max_length=100, null=True, verbose_name='Rin'),
        ),
        migrations.AlterField(
            model_name='llanta',
            name='fabricante',
            field=models.CharField(max_length=100, null=True, verbose_name='Fabricante'),
        ),
    ]
