# Generated by Django 4.1.1 on 2022-10-06 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_llantas', '0004_remove_llanta_descripcion_llanta_ancho_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llanta',
            name='indiceCarga',
            field=models.CharField(choices=[(10, 10), (20, 20)], max_length=100, null=True, verbose_name='Indice de Carga'),
        ),
    ]
